### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by blennerSilva** [nidhinvv/BubbleAlert#1]
how do i compile this on my project?

**Comment by imne** [comment]
The screenshots look good but there aren't any actual code examples/snippets

**Comment by nidhinvv** [comment]
I will update. did u check the source code?

**Comment by nidhinvv** [comment]
I have change the code. You can now use the lib module in your projects.

**Comment by imne** [comment]
Can you add it to the read me

**Comment by nidhinvv** [comment]
@imne :  you can check now

**Comment by nidhinvv** [comment]
https://github.com/nidhinvv/BubbleAlert/blob/master/README.md

check this one
